<?php

$tickets = $this->getTickets();

?>

<div class="my-account">


    <div class="page-title title-buttons">
        <h1><?php echo $this->__('My Tickets') ?></h1>

        <form method="get" action="<?php echo $this->getUrl('tickets/action/new') ?>">
        <button type="submit" class="button" ><span><span><?php echo $this->__('Add New Ticket') ?></span></span></button>
        </form>

    </div>



<?php if($tickets->getData()): ?>

    <table class="data-table" id="my-tickets-table" >

        <thead>
        <tr>
            <th><?php echo $this->__('Ticket ID #') ?></th>
            <th><?php echo $this->__('Subject') ?></th>
            <th><?php echo $this->__('Date') ?></th>
            <th><?php echo $this->__('Status') ?></th>
            <th><?php echo $this->__('Action') ?></th>

        </tr>
        </thead>
        <tbody>
        <?php foreach ($tickets as $ticket): ?>
            <tr>
                <td><?php echo $ticket->getTicketId() ?>&nbsp;</td>
                <td><?php echo $this->escapeHtml($ticket->getSubject()) ?>&nbsp;</td>
                <td><?php echo $ticket->getCreatedAt() ?>&nbsp;</td>
                <td><?php echo $ticket->getStatus() ? 'Active' : 'Closed' ?>&nbsp;</td>
                <td><a href="<?php echo $this->getUrl('tickets/action/view', array('ticket_id'=>$ticket->getTicketId())) ?>"><?php echo $this->__('View Ticket') ?></a>&nbsp;</td>
            </tr>
        <?php endforeach ?>
        </tbody>
    </table>
    <script type="text/javascript">decorateTable('my-tickets-table')</script>
<?php else: ?>
    <p><?php echo $this->__('There are no tickets yet..') ?></p>
<?php endif ?>
<div class="buttons-set">
    <p class="back-link"><a href="<?php echo $this->getUrl('customer/account') ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
</div>


</div>